language: nix
env:
  - SERVER_IP_ADDRESS=52.23.228.46

before_install:
- openssl aes-256-cbc -K $encrypted_9b425f3af6a6_key -iv $encrypted_9b425f3af6a6_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 700 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key root@$SERVER_IP_ADDRESS pwd
- PATH_TO_BUILD=$(nix-build --attr project release.nix --no-out-link)
- nix-copy-closure --to --use-substitutes $SERVER_IP_ADDRESS $PATH_TO_BUILD
